### ISSUE TITLE
I think I broke the bot on astropy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#26]
Sorry!

**Comment by pllim** [comment]
I try to debug it locally like this:
```python
from changebot.github_api import IssueHandler

issue = IssueHandler('astrofrog/test-bot', '2', None)
issue.submit_comment('Testing whether pllim broke the bot')
```
but it needs authentication now:
```
(py36) prompt> python testtest.py 
Traceback (most recent call last):
  File "testtest.py", line 8, in <module>
    issue.submit_comment('Testing whether pllim broke the bot')
  File ".../astropy-bot/changebot/github_api.py", line 212, in submit_comment
    assert response.ok, response.content
AssertionError: b'{"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"}'
```

**Comment by astrofrog** [comment]
Yes I need to document how to use it locally :)

**Comment by astrofrog** [comment]
The bot is now fixed and I've documented how to run it locally in https://github.com/astropy/astropy-bot/blob/master/README.md
